### ISSUE TITLE
How to write a test for flutter_i18n

### ISSUE THREAD

**Issue by jjerome00** [long1eu/flutter_i18n#12]
Is it possible to write tests when using this library?  I've tried a few different ways of building the test widget, but I always get the same error message.

strings_en.arb
```
{
  "login": "LOGIN"
}
```

i18n_test.dart
```
import 'package:ad_mobile_flutter/generated/i18n.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "test",
      localizationsDelegates: [S.delegate],
      supportedLocales: S.delegate.supportedLocales,
      localeResolutionCallback: S.delegate.resolution(fallback: new Locale("en", "")),
      locale: new Locale("en", ""),
      home: Scaffold(
        body: Container(
          child: Text(S.of(context).login),
          key: Key('login'),
        ),
      ),
    );
   }
}

void main() {
  testWidgets('locale test', (WidgetTester tester) async {
    await tester.pumpWidget(TestWidget());
  });
}
```

This results in:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building TestWidget(dirty):
The getter 'login' was called on null.
Receiver: null
Tried calling: login

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      TestWidget.build (file:///Users/jmj/Documents/Development/level11/ad_mobile_flutter/test/i18n_test.dart:17:37)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3695:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[38 more...]
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by long1eu** [comment]
Good question. Didn't tried it myself. I'll take a look.

**Comment by jjerome00** [comment]
I figured it out.  For some reason I need to create a widget class to pass into the tester.  I added a working example below. 

strings_en.arb:
```
{
  "app_title": "My App Title"
}
```

i18n_test.dart
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:myapp_mobile/generated/i18n.dart';

class WidgetUnderTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [S.delegate],
      supportedLocales: S.delegate.supportedLocales,
      localeResolutionCallback: S.delegate.resolution(fallback: new Locale("en", "")),
      home: Center(child: Text(S.of(context).app_title)),
    );
  }
}

void main() {

  testWidgets('Uses strings from i18n library', (WidgetTester tester) async {
    // GIVEN I create the app with internationalization support (i18n)
    await tester.pumpWidget(MaterialApp(
      home: WidgetUnderTest(),
      localizationsDelegates: [S.delegate],
      supportedLocales: S.delegate.supportedLocales,
      localeResolutionCallback: S.delegate.resolution(fallback: new Locale("en", "")),
    ));

    // WHEN I search for a string that is supplied by the library (S.of(context).app_title)
    // THEN I find it
    expect(find.text("My App Title"), findsOneWidget);
  });

}
```

**Comment by ykorzikowski** [comment]
Please add this to README 👍

**Comment by haarts** [comment]
Wait. You're nesting two MaterialApp widgets? That seems counter intuitive.

**Comment by niltonvasques** [comment]
Doesnt make much sense this nesting :thinking:  Is this the recommended way?
