### ISSUE TITLE
MaterialLocalizations error 

### ISSUE THREAD

**Issue by wamisnet** [long1eu/flutter_i18n#17]
https://github.com/flutter/flutter/commit/9bf8502fef3f35d8d3ba692ce0383e9f55a34624

Since this commit, when multilingualization is done, the application spits out an error.

```
I/flutter ( 9104): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9104): The following assertion was thrown building AppBar(dirty, state: _AppBarState#4c5fd):
I/flutter ( 9104): No MaterialLocalizations found.
I/flutter ( 9104): AppBar widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
I/flutter ( 9104): Localizations are used to generate many different messages, labels,and abbreviations which are used
I/flutter ( 9104): by the material library. 
I/flutter ( 9104): To introduce a MaterialLocalizations, either use a  MaterialApp at the root of your application to
I/flutter ( 9104): include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
I/flutter ( 9104): The specific widget that could not find a MaterialLocalizations ancestor was:
I/flutter ( 9104):   AppBar
I/flutter ( 9104):   LayoutId-[<_ScaffoldSlot.appBar>](id: _ScaffoldSlot.appBar)
I/flutter ( 9104): 
I/flutter ( 9104): When the exception was thrown, this was the stack:
I/flutter ( 9104): #0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:124:7)
I/flutter ( 9104): #1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:127:4)
I/flutter ( 9104): #2      _AppBarState.build (package:flutter/src/material/app_bar.dart:336:12)
I/flutter ( 9104): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
I/flutter ( 9104): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)

```

**Comment by krossenk** [comment]
Solved this issue by adding following in pubspec:
```
flutter_localizations:
    sdk: flutter
```
And in main instantiation of app:
```
return MaterialApp(
      ....
      debugShowCheckedModeBanner: false,
      localizationsDelegates: [S.delegate, GlobalMaterialLocalizations.delegate],
      supportedLocales: S.delegate.supportedLocales,
      )
```
`GlobalMaterialLocalizations.delegate` fixed it for me

**Comment by drriguz** [comment]
@krossenk  Works for me too, but I don't know why.....
