### ISSUE TITLE
Flutter change breaks LocaleResolutionCallback

### ISSUE THREAD

**Issue by jjerome00** [long1eu/flutter_i18n#18]
I started seeing errors when trying to run on iOS.  
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building IconTheme(IconThemeData#2abdc(color:
Color(0xdd000000))):
The getter 'languageCode' was called on null.
Receiver: null
Tried calling: languageCode

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      GeneratedLocalizationsDelegate.resolution.<anonymous closure> (package:americandream/generated/i18n.dart:99:55)
#2      _WidgetsAppState._resolveLocale (package:flutter/src/widgets/app.dart:682:36)
#3      _WidgetsAppState.initState (package:flutter/src/widgets/app.dart:566:15)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3791:58)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3657:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```
See these issues:
https://github.com/flutter/flutter/issues/24064
https://github.com/flutter/flutter/issues/24288

I was able to workaround this issue:
1. Disable the `flutter_i18n` plugin in Android Studio
2. Updated the `resolution({Locale fallback})` function in my `generated/i18n.dart` file like so:
```
  LocaleResolutionCallback resolution({Locale fallback}) {
    return (Locale locale, Iterable<Locale> supported) {

      if (locale == null || !isSupported(locale) ) {
        final Locale fallbackLocale = fallback ?? supported.first;
        return fallbackLocale;
      }

      final Locale languageLocale = new Locale(locale.languageCode, "");
      if (supported.contains(locale))
        return locale;
      else if (supported.contains(languageLocale))
        return languageLocale;
      else {
        final Locale fallbackLocale = fallback ?? supported.first;
        return fallbackLocale;
      }
    };
  }
```

Obviously this is not an ideal situation.  I can't keep the plugin disabled.

**Comment by hyochan** [comment]
This still happening from `10.0.0` to recent version. I've just tested this and it works fine until flutter version `0.9.6`.

**Comment by noordawod** [comment]
I can send a PR to fix this, @dooboolab @long1eu.

**Comment by long1eu** [comment]
perfect

**Comment by noordawod** [comment]
Here you go @long1eu: https://github.com/long1eu/flutter_i18n/pull/19
All credit goes to @jjerome00 for the fix!

**Comment by noordawod** [comment]
All credit goes to @jjerome00 for the fix!

**Comment by noordawod** [comment]
@long1eu this can be closed now I believe.
