### ISSUE TITLE
Plugin stopped generating i18n.dart file

### ISSUE THREAD

**Issue by talmor-guy** [long1eu/flutter_i18n#29]
My plugin stopped generating the i18n file, I am guessing some upgrade of the plugin or flutter broke it.
Tried to uninstall and reinstall the plugin and got this exception:

No match found
java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at java.util.regex.Matcher.group(Matcher.java:496)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator$appendPluralMethod$parameterName$1.invoke(I18nFileGenerator.kt:205)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator$appendPluralMethod$parameterName$1.invoke(I18nFileGenerator.kt:20)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator.appendPluralMethod$i18n(I18nFileGenerator.kt:203)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator.appendSClass(I18nFileGenerator.kt:87)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator.generate(I18nFileGenerator.kt:42)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1$lambda$1.compute(actions.kt:70)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:917)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1.run(Timer.kt:146)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

I am not using plurals syntax in my arb file.

**Comment by long1eu** [comment]
#26
