### ISSUE TITLE
Issue with Android Studio: Write access is allowed inside write-action only

### ISSUE THREAD

**Issue by ammachado** [long1eu/flutter_i18n#47]
Got this exception on a project without fiddling with `misc.xml` or anything else.  Just installed the plugin and the error popped out.

Android Studio 3.3.1
Build #AI-182.5107.16.33.5264788, built on January 28, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

`java.lang.Throwable: Assertion failed: Write access is allowed inside write-action only (see com.intellij.openapi.application.Application.runWriteAction())
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:169)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertWriteAccessAllowed(ApplicationImpl.java:1345)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvent(PersistentFSImpl.java:686)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.createChildFile(PersistentFSImpl.java:450)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.createChildData(VirtualFileSystemEntry.java:217)
	at com.intellij.openapi.vfs.VirtualFile.findOrCreateChildData(VirtualFile.java:322)
	at eu.long1.flutter.i18n.files.FileHelpers.getI18nFile(FileHelpers.kt:23)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator.generate(I18nFileGenerator.kt:54)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1$lambda$1.compute(actions.kt:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:945)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1.run(Timer.kt:150)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)`

Edit to fix formatting.

**Comment by lionnung** [comment]
I also got this error. @@

**Comment by noordawod** [comment]
Which IDE are you using? Is this still an issue?

**Comment by esfomeado** [comment]
I also go this problem on Android Studio 3.3.2.

**Comment by arturomf** [comment]
I have this problem on Android Studio 3.4

**Comment by Purus** [comment]
I am using Android 3.4 and got this issue too.. But it's not a blocking issue.

**Comment by Jon-Salmon** [comment]
I'm having this issue on a fresh install of Android studio 3.4 running on macOS 14.4.4

The plugin isn't generating any compiled files.

**Comment by wrozwad** [comment]
plugin: `1.0.2`
IDE: `Android Studio 3.4.1` which based on `IntelliJ IDEA 2018.3.4`
system: `Windows 10 Home 1803`

**Comment by noordawod** [comment]
This is now resolved in v1.1.0. Please upgrade through the Plugins page in your IDE.
