### ISSUE TITLE
java.lang.AssertionError: Already disposed: Project (Disposed) xxxxxxx

### ISSUE THREAD

**Issue by csshuai** [long1eu/flutter_i18n#56]
```
java.lang.AssertionError: Already disposed: Project (Disposed) xxxxxxx
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:248)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:246)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:239)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:149)
	at com.intellij.psi.PsiManager.getInstance(PsiManager.java:39)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator.<init>(I18nFileGenerator.kt:22)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1$lambda$1.compute(actions.kt:70)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:945)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1.run(Timer.kt:146)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by noordawod** [comment]
@csshuai 

Thanks for the report.

Please provide:

- `flutter doctor` output.
- flutter_i18n plugin version.
- IDE version (Help > About), screenshot would be best.

Thanks in advance!

**Comment by csshuai** [comment]
```
flutter doctor -v
[✓] Flutter (Channel dev, v1.4.10, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.4.10 at /Users/william/git/dart/flutter
    • Framework revision 6ba720a489 (7 days ago), 2019-04-04 11:27:41 -0400
    • Engine revision 5944867cab
    • Dart version 2.2.1 (build 2.2.1-dev.3.0 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/william/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/william/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/william/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Users/william/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.87

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (3 available)
    • MI 4LTE   • 9121afb0                                 • android-arm • Android 6.0.1 (API 23)
    • shuai     • 5b30d26812772b8c450df62891c6f7ede83702af • ios         • iOS 12.2
    • iPhone Xʀ • CC06E74A-5414-40EF-9D0B-B59712EF14D5     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

flutter_i18n: `1.0.3`

![image](https://user-images.githubusercontent.com/1501906/55951445-d8422800-5c89-11e9-9e4a-f70064ff2f07.png)

**Comment by noordawod** [comment]
Perfect, thanks! Will schedule it for a next release, this should take a short fix.

**Comment by PerLycke** [comment]
@noordawod this error still occurs regularly on latest release and Android Studio. Can I provide some logs for you to squash this bug? :)

**Comment by noordawod** [comment]
Very strange bug indeed. I don't recall ever seeing it on my end...
Well, by all means, fire away your logs :)

**Comment by noordawod** [comment]
This should be fixed now.
Please re-open if the problem persists after the latest plugin release.

**Comment by PerLycke** [comment]
@noordawod Got this just now on version 1.1.4-191. Log:

`java.lang.AssertionError: Already disposed: Project (Disposed) car_info_app
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:245)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:243)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:236)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:46)
	at com.intellij.project.ProjectKt.getStateStore(project.kt:17)
	at com.intellij.openapi.project.impl.ProjectImpl.getStateStore(ProjectImpl.java:178)
	at com.intellij.openapi.project.impl.ProjectImpl.getProjectFile(ProjectImpl.java:207)
	at eu.long1.flutter.i18n.files.FileHelpers.getPubSpecConfig(FileHelpers.kt:41)
	at eu.long1.flutter.i18n.files.FileHelpers.shouldActivateFor(FileHelpers.kt:53)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator.generate(I18nFileGenerator.kt:29)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1$lambda$1$1.compute(actions.kt:74)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$19(ApplicationImpl.java:1065)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1021)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1065)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1$lambda$1.run(Initializer.kt:286)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by noordawod** [comment]
Thanks @PerLycke. Can you please describe the steps to reproduce this?

**Comment by PerLycke** [comment]
1. Open project
2. Switch theme (I switched from dracula to light theme)
3. Close project (so that you end up on the Android Studio start screen)

I did exactly this and the error occured, hope it helps. I have no idea if the theme switching is relevant at all though :)

**Comment by noordawod** [comment]
Thanks! I'll check if I can reproduce this locally.
