### ISSUE TITLE
Not working with latest Flutter & IntelliJ

### ISSUE THREAD

**Issue by permadart** [long1eu/flutter_i18n#66]
This plugin just stopped working with yesterday's Flutter and recent IntelliJ update. Keeps giving an error and doesn't generate the getters for the Strings. Can it be updated to make it work with newest tools? Thanks.

**Comment by necessitudo** [comment]
In last version of Android Studio i get next error -
java.lang.ClassCastException: com.intellij.psi.impl.source.PsiPlainTextFileImpl cannot be cast to com.intellij.json.psi.JsonFile
	at eu.long1.flutter.i18n.workers.I18nFileGenerator.generate(I18nFileGenerator.kt:34)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1$lambda$1.compute(actions.kt:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:963)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1.run(Timer.kt:150)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

Цhat is it?

**Comment by noordawod** [comment]
Thanks for reporting it, @herrmartell. I'll take a look this week.

**Comment by cirediew** [comment]
This seems to be the same as #53

**Comment by noordawod** [comment]
This will be fixed once #98 is merged.

**Comment by noordawod** [comment]
This is now resolved in v1.1.0. Please upgrade through the Plugins page in your IDE.
